### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by skynet-jzm** [jjonhwa/Cross-Encoder-with-Bi-Encoder#3]
wikipedia_documents.json can`t download

**Comment by jjonhwa** [comment]
Hi @skynet-jzm , Thanks for your interest in my work.

I modified the code for `!gdown`, so please try again. Thank you for pointing out the error.

**Comment by skynet-jzm** [comment]
> Hi @skynet-jzm , Thanks for your interest in my work.
> 
> I modified the code for `!gdown`, so please try again. Thank you for pointing out the error.

Hi @jjonhwa ,Thanks for your reply ,and error still exists,such as the picture blow
![image](https://user-images.githubusercontent.com/72917683/182820123-fb5b0902-021e-4f06-b224-498c8303cb69.png)

**Comment by jjonhwa** [comment]
Ah! I mean that I modified the code on Readme.

Please use this code :)
`!gdown --id 1OSKOeZxVmjRWokMCNiFtpOQuFDArNINf`
